apply plugin: 'com.android.application'
apply plugin: 'io.michaelrocks.paranoid'
apply plugin: 'AndResGuard'

android {
    compileSdkVersion 31
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "app.dev.shapla.vpn"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 100
        versionName "1.0"
        setProperty("archivesBaseName", "$applicationId-$versionName-(Build$versionCode)")
        ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a'
        }
    }
    signingConfigs {
        release {
            storeFile file("../key/renz_keystore.jks")
            storePassword "google"
            keyAlias "googlekey"
            keyPassword "google"
        }
        debug {
            storeFile file("../key/renz_keystore.jks")
            storePassword "google"
            keyAlias "googlekey"
            keyPassword "google"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError false
    }
}
andResGuard {
    mappingFile = null
    use7zip = false
    useSign = true
    keepRoot = false
    fixedResName = "arg"
    mergeDuplicatedRes = true
    whiteList = [
            "R.drawable.icon",
            "R.string.com.crashlytics.*",
            "R.string.google_app_id",
            "R.string.gcm_defaultSenderId",
            "R.string.default_web_client_id",
            "R.string.ga_trackingId",
            "R.string.firebase_database_url",
            "R.string.google_api_key",
            "R.string.google_crash_reporting_api_key",
            "R.string.project_id",
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
    ]
    sevenzip {
        artifact = 'com.tencent.mm:SevenZip:1.2.21'
    }
    finalApkBackupPath = "${project.rootDir}/final.apk"
}
dependencies {
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'com.scottyab:rootbeer-lib:0.1.0'
    implementation project(':MPChartLib')
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.github.angads25:filepicker:1.1.1'
    implementation 'junit:junit:4.13.2'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
